FROM node:20-alpine
WORKDIR /app
COPY package*.json ./
COPY prisma ./prisma/
RUN npm ci
COPY . .
RUN npx prisma generate
RUN npm run build
EXPOSE 3000
ENV SERVICE_TYPE=api
CMD ["sh", "-c", "npx prisma migrate deploy && node dist/app.js"]
