import dotenv from 'dotenv';

dotenv.config();

export const config = {
  databaseUrl: process.env.DATABASE_URL || '',
  redisUrl: process.env.REDIS_URL || 'redis://localhost:6379',
  enableRedis: process.env.ENABLE_REDIS === 'true',
  enableWebSocketRedisAdapter: process.env.ENABLE_WEBSOCKET_REDIS_ADAPTER === 'true',
  jwtSecret: process.env.JWT_SECRET || 'your_jwt_secret',
  jwtRefreshSecret: process.env.JWT_REFRESH_SECRET || 'your_refresh_secret',
  claudeApiKey: process.env.CLAUDE_API_KEY || process.env.ANTHROPIC_API_KEY || '',
  geminiApiKey: process.env.GEMINI_API_KEY || process.env.GOOGLE_GENERATIVE_AI_API_KEY || process.env.GOOGLE_API_KEY || '',
  geminiModel: process.env.GEMINI_MODEL || 'gemini-2.5-flash-lite',
  googleTtsApiKey: process.env.GOOGLE_TTS_API_KEY || '',
  elevenLabsApiKey: process.env.ELEVENLABS_API_KEY || '',
  elevenLabsVoiceId: process.env.ELEVENLABS_VOICE_ID || 'JBFqnCBsd6RMkjVDRZzb',
  elevenLabsModelId: process.env.ELEVENLABS_MODEL_ID || 'eleven_flash_v2_5',
  googleVisionApiKey: process.env.GOOGLE_VISION_API_KEY || '',
  googleOauthClientId: process.env.GOOGLE_OAUTH_CLIENT_ID || 'dummy_client_id',
  googleOauthClientSecret: process.env.GOOGLE_OAUTH_CLIENT_SECRET || '',
  r2AccountId: process.env.R2_ACCOUNT_ID || '',
  r2AccessKey: process.env.R2_ACCESS_KEY || '',
  r2SecretKey: process.env.R2_SECRET_KEY || '',
  r2BucketName: process.env.R2_BUCKET_NAME || 'akademi-files',
  r2PublicUrl: process.env.R2_PUBLIC_URL || '',
  resendApiKey: process.env.RESEND_API_KEY || 're_dummy_key',
  typesenseHost: process.env.TYPESENSE_HOST || 'localhost',
  typesensePort: parseInt(process.env.TYPESENSE_PORT || '8108', 10),
  typesenseApiKey: process.env.TYPESENSE_API_KEY || '',
  typesenseProtocol: process.env.TYPESENSE_PROTOCOL || 'https',
  typesenseAutoSync: process.env.TYPESENSE_AUTO_SYNC === 'true',
  paystackSecretKey: process.env.PAYSTACK_SECRET_KEY || '',
  paystackWebhookSecret: process.env.PAYSTACK_WEBHOOK_SECRET || '',
  sentryDsn: process.env.SENTRY_DSN || null,
  sentryEnvironment: process.env.SENTRY_ENVIRONMENT || process.env.NODE_ENV || 'development',
  sentryRelease: process.env.SENTRY_RELEASE || 'akademi-backend@1.0.0',
  port: parseInt(process.env.PORT || '3000', 10),
  nodeEnv: process.env.NODE_ENV || 'development',
  serviceType: process.env.SERVICE_TYPE || 'api',
  unlockAllFeatures: process.env.UNLOCK_ALL_FEATURES === 'true',
  tournamentActivationIntervalMs: parseInt(process.env.TOURNAMENT_ACTIVATION_INTERVAL_MS || '15000', 10),
  adminReingestSecret: process.env.ADMIN_REINGEST_SECRET || '',
};
