import * as Print from "expo-print";
import * as Sharing from "expo-sharing";

import { buildMathHtmlContent } from "../components/ui/RichMathText";

export interface SolutionPdfEntry {
  index: number;
  question: string;
  answer: string;
}

export interface ExportSolutionsPdfResult {
  uri: string;
  shared: boolean;
}

const escapeHtml = (value: string) =>
  value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");

const buildEntryHtml = (entry: SolutionPdfEntry, isLast: boolean) => `
  <section class="entry" style="${isLast ? "" : "page-break-after: always;"}">
    <div class="label">QUESTION ${entry.index + 1}</div>
    <div class="content question-content">${buildMathHtmlContent(entry.question)}</div>
    <div class="label answer-label">AKADEMI SYNTHESIS</div>
    <div class="content">${buildMathHtmlContent(entry.answer)}</div>
  </section>
`;

const buildDocumentHtml = (entries: SolutionPdfEntry[], title: string, subtitle?: string) => `
<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
    <script src="https://cdn.jsdelivr.net/npm/katex@0.16.10/dist/katex.min.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.10/dist/katex.min.css">
    <script src="https://cdn.jsdelivr.net/npm/katex@0.16.10/dist/contrib/auto-render.min.js"></script>
    <style>
      html, body {
        margin: 0;
        padding: 0;
        background: #FFFFFF;
        color: #111827;
      }
      body {
        font-family: Georgia, 'Times New Roman', serif;
        font-size: 14px;
        line-height: 1.6;
        padding: 32px 36px;
      }
      .doc-header {
        border-bottom: 2px solid #16A34A;
        margin-bottom: 24px;
        padding-bottom: 12px;
      }
      .doc-title {
        font-size: 20px;
        font-weight: 700;
        margin: 0 0 4px 0;
      }
      .doc-subtitle {
        font-family: Arial, sans-serif;
        font-size: 11px;
        color: #6B7280;
        margin: 0;
      }
      .entry {
        margin-bottom: 28px;
      }
      .label {
        font-family: 'Courier New', monospace;
        font-size: 10px;
        letter-spacing: 0.06em;
        color: #6B7280;
        margin-bottom: 8px;
      }
      .answer-label {
        margin-top: 18px;
      }
      .content {
        word-break: break-word;
      }
      .paragraph {
        margin: 0 0 0.6em 0;
      }
      .math-line {
        margin: 0.2em 0 0.5em 0;
      }
      ul {
        margin: 0 0 0.7em 1.2em;
        padding: 0;
      }
      li {
        margin: 0 0 0.35em 0;
      }
      .katex-display {
        margin: 0.3em 0;
        overflow-x: visible;
      }
      .doc-footer {
        margin-top: 32px;
        padding-top: 12px;
        border-top: 1px solid #E5E7EB;
        font-family: Arial, sans-serif;
        font-size: 10px;
        color: #9CA3AF;
      }
    </style>
  </head>
  <body>
    <div class="doc-header">
      <p class="doc-title">${escapeHtml(title)}</p>
      ${subtitle ? `<p class="doc-subtitle">${escapeHtml(subtitle)}</p>` : ""}
    </div>
    ${entries.map((entry, i) => buildEntryHtml(entry, i === entries.length - 1)).join("")}
    <div class="doc-footer">Generated by Akademi</div>
    <script>
      try {
        if (window.renderMathInElement) {
          renderMathInElement(document.body, {
            throwOnError: false,
            strict: 'ignore',
            delimiters: [
              { left: '$$', right: '$$', display: true },
              { left: '\\\\[', right: '\\\\]', display: true },
              { left: '\\\\(', right: '\\\\)', display: false },
              { left: '$', right: '$', display: false }
            ]
          });
        }
      } catch (error) {}
    </script>
  </body>
</html>`;

export const exportSolutionsAsPdf = async (
  entries: SolutionPdfEntry[],
  options?: { title?: string; subtitle?: string }
): Promise<ExportSolutionsPdfResult> => {
  if (!entries.length) {
    throw new Error("There is nothing to export yet.");
  }

  const html = buildDocumentHtml(entries, options?.title || "Akademi Solution", options?.subtitle);
  const { uri } = await Print.printToFileAsync({ html, base64: false });

  const canShare = await Sharing.isAvailableAsync();
  if (canShare) {
    await Sharing.shareAsync(uri, {
      mimeType: "application/pdf",
      dialogTitle: options?.title || "Akademi Solution",
      UTI: "com.adobe.pdf",
    });
  }

  return { uri, shared: canShare };
};
